### ISSUE TITLE
##[warning]Failed to generate Html report. Error: null

### ISSUE THREAD

**Issue by edag94** [MicrosoftDocs/azure-devops-docs#10567]
I am getting an issue generating an HTML report using the cobertura reporter for Jest. 

I am getting the same issue as referenced below
`##[warning]Please install dotnet core to enable automatic generation of Html report.`

I then proceeded to add a UseDotnet task:

```yaml
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 2.2.203
    installationPath: $(Agent.ToolsDirectory)/dotnet
```

On the subsequent run, I get this log:

```text
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
##[warning]Failed to generate Html report. Error: null
```

I'm not sure what to do with this message. I have tried different versions of the SDK, with no luck.

_Originally posted by @edag94 in https://github.com/MicrosoftDocs/azure-devops-docs/issues/4639#issuecomment-824335710_

**Comment by edag94** [comment]
I referenced the comment on the old issue that is relevant to this one

**Comment by edag94** [comment]
Closing, will post in Azure Pipelines Task instead
