### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mcurko** [MicrosoftDocs/azure-devops-docs#5944]
After the step 12/13, this is the result of a PR creation (along with 500 internal error):

TypeError: Cannot read property 'resource' of undefined
    at C:\Temp\pr-server\app.js:15:27
    at Layer.handle [as handle_request] (C:\Temp\pr-server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Temp\pr-server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Temp\pr-server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Temp\pr-server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Temp\pr-server\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Temp\pr-server\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Temp\pr-server\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Temp\pr-server\node_modules\express\lib\middleware\init.js:40:5)
    at Layer.handle [as handle_request] (C:\Temp\pr-server\node_modules\express\lib\router\layer.js:95:5)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8f48d8a-33fb-9f6d-1db1-4cccb5b987d9
* Version Independent ID: 3e18fcbf-331d-9de2-62ae-c4e7c888cc48
* Content: [Create a pull request status server with Node.js - Azure Repos](https://docs.microsoft.com/en-us/azure/devops/repos/git/create-pr-status-server?view=azure-devops#feedback)
* Content Source: [docs/repos/git/create-pr-status-server.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/repos/git/create-pr-status-server.md)
* Product: **devops**
* Technology: **devops-code-git**
* GitHub Login: @apawast
* Microsoft Alias: **apawast**

**Comment by sdbzcm** [comment]
After Step 13 from "Post Status To PR" topic, got TypeError: Cannot read property 'value' of null
    at areaLocationsPromise.restClient.options.then
