### ISSUE TITLE
Tried to queue_build using python client but got too many 502 error responses

### ISSUE THREAD

**Issue by zhenbang-databricks** [MicrosoftDocs/azure-devops-docs#8086]
```
Got the following issue when trying to use the python client to trigger a build.
Traceback (most recent call last):
  File "/Users/zhenbang.liu/Desktop/python_scripts/azure_devops.py", line 28, in <module>
    build_client.queue_build(build, project.name)
  File "/usr/local/lib/python2.7/site-packages/azure/devops/released/build/build_client.py", line 314, in queue_build
    content=content)
  File "/usr/local/lib/python2.7/site-packages/azure/devops/client.py", line 104, in _send
    response = self._send_request(request=request, headers=headers, content=content, media_type=media_type)
  File "/usr/local/lib/python2.7/site-packages/azure/devops/client.py", line 63, in _send_request
    content=content, **operation_config)
  File "/usr/local/lib/python2.7/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/usr/local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/usr/local/lib/python2.7/site-packages/msrest/universal_http/requests.py", line 145, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/usr/local/lib/python2.7/site-packages/msrest/exceptions.py", line 54, in raise_with_traceback
    raise error
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='dev.azure.com', port=443): Max retries exceeded with url: /zhenbangliu/test/_apis/build/Builds (Caused by ResponseError('too many 502 error responses',))

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9e313c5-9120-9172-bc27-c21d10fcd5ae
* Version Independent ID: 1a837182-591f-3cbc-1632-7b50d857b13c
* Content: [Release triggers for stages, branches, and pipelines - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops)
* Content Source: [docs/pipelines/release/triggers.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/release/triggers.md)
* Product: **devops**
* Technology: **devops-cicd-release**
* GitHub Login: @RoopeshNair
* Microsoft Alias: **ronai**

**Comment by msebolt** [comment]
@zhenbang-databricks Thank you for the feedback, we're sorry for the difficulties.

Does this issue apply to an example in the article?  If so, please provide any details below.

With user-specific scenarios, provided support in the documentation forum is limited unfortunately. For additional support options, please refer to:

- [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html)
- [Azure DevOps Support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now.  For related posts on 502 errors, see [here](https://developercommunity.visualstudio.com/content/problem/484401/azure-devops-cicd-release-pipeline-for-function-ap.html).
