### ISSUE TITLE
PublishBuildArtifacts behind Proxy fails on Linux with CurlException

### ISSUE THREAD

**Issue by cawoodm** [MicrosoftDocs/azure-devops-docs#8566]
We're getting `Net.Http.CurlException` on our Linux on-prem machines (Agent version 1.169.0) behind a proxy (Windows machine is fine). The proxy is correctly configured and the pipeline/agent is successful in connecting to the internet, cloning the repo etc. When we do `curl` we can access the internet from the machine. We have the variables `http_proxy`, `https_proxy` and `no_proxy` set appropriately.

What proxy settings does this task respect?

```
2020-06-08T08:55:46.2850827Z Task         : Publish build artifacts
2020-06-08T08:55:46.2851285Z Description  : Publish build artifacts to Azure Pipelines or a Windows file share
2020-06-08T08:55:46.2851587Z Version      : 1.158.2
2020-06-08T08:55:46.2851801Z Author       : Microsoft Corporation
2020-06-08T08:55:46.2852129Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/publish-build-artifacts
2020-06-08T08:55:46.2852519Z ==============================================================================
2020-06-08T08:55:46.5298433Z ##[section]Async Command Start: Upload Artifact
2020-06-08T08:55:46.5298671Z Uploading 17867 files
2020-06-08T08:55:51.5324165Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:56:01.5446835Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:56:11.8967116Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:56:21.9047373Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:56:31.9098325Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:56:41.9122637Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:56:51.9126076Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:57:01.9124428Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:57:11.9147429Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:57:21.9166190Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:57:31.9223804Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:57:41.9261391Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:57:51.9307156Z Total file: 17867 ---- Processed file: 0 (0%)
2020-06-08T08:58:01.4292415Z Fail to upload '/prg/azure/build/_work/9/s/.gitignore' due to 'An error occurred while sending the request.'.
2020-06-08T08:58:01.4295556Z System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Boolean uploadFirstChunk, Object userState, Boolean compressStream)
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.FileContainerServer.UploadAsync(IAsyncCommandContext context, Int32 uploaderId, CancellationToken token)
2020-06-08T08:58:01.4298844Z Detail upload trace for file that fail to upload: PartsLinux/.gitignore
2020-06-08T08:58:01.4299165Z File 'PartsLinux/.gitignore' will be uploaded in one chunk.
2020-06-08T08:58:01.4299480Z Attempt '1' for uploading chunk '1' of file 'PartsLinux/.gitignore'.
2020-06-08T08:58:01.4299879Z Generate new HttpRequest for uploading file 'PartsLinux/.gitignore', chunk '1' of '1'.
2020-06-08T08:58:01.4300344Z Start uploading file 'PartsLinux/.gitignore' to server, chunk '1'.
2020-06-08T08:58:01.4302972Z Chunk '1' attempt '1' of file 'PartsLinux/.gitignore' fail to send request to server. Error: System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.CurlException: Failure when receiving data from the peer
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.FileContainer.Client.FileContainerHttpClient.UploadFileAsync(Int64 containerId, String itemPath, Stream fileStream, Byte[] contentId, Int64 fileLength, Boolean isGzipped, Guid scopeIdentifier, CancellationToken cancellationToken, Int32 chunkSize, Int32 chunkRetryTimes, Boolean uploadFirstChunk, Object userState).
2020-06-08T08:58:01.4305328Z Backoff 5.904 seconds before attempt '2' chunk '1' of file 'PartsLinux/.gitignore'.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acd43f88-bb0b-e6c1-3a1d-c34af9a11dfb
* Version Independent ID: 282eb416-bb03-9553-dbc2-71bb71191c73
* Content: [Publish Build Artifacts task - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops)
* Content Source: [docs/pipelines/tasks/utility/publish-build-artifacts.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/tasks/utility/publish-build-artifacts.md)
* Product: **devops**
* Technology: **devops-cicd-tasks**
* GitHub Login: @vijayma
* Microsoft Alias: **vijayma**

**Comment by msebolt** [comment]
@cawoodm  Thank you for the feedback.

Unfortunately our support options here are limited to documentation examples only.

Please use **Report a problem** or **Suggest a feature** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html) to solicit feedback from the product team.

Otherwise, for additional support options, see:

- [Azure DevOps support](https://azure.microsoft.com/support/devops/)
- [Azure DevOps on StackOverflow](https://stackoverflow.com/questions/tagged/azure-devops)

**Comment by msebolt** [comment]
Closing this issue now, please refer to [agent proxy](https://docs.microsoft.com/azure/devops/pipelines/agents/proxy) for additional support.
