### ISSUE TITLE
Unable to auth agent with PAT. "Basic authentication requires a secure connection to the server."

### ISSUE THREAD

**Issue by Stahhl** [MicrosoftDocs/azure-devops-docs#9670]
Original issue is running a self-contained dockeragent. But im also getting the same result running [self-hosted windows agent](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-windows?view=azure-devops). And i honestly dont know how to read logs inside a not running container. So i'll be using windows in my issue.

**Tried running agent on**
- Docker (host: RHEL7 30, container: ubuntu 18.04)
- Windows 10

**Trying to connect to**
- On-prem azure devops server

This is the result of running the config.cmd from an elevated powershell.

<pre><code>
PS C:\Utveckling\devopsagentwindows> ./config.cmd    
Enter server URL > http://server:8080/tfs/project
Enter authentication type (press enter for Integrated) > pat
Enter personal access token > ****************************************************
Basic authentication requires a secure connection to the server.
Failed to connect.  Try again or ctrl-c to quit
Enter server URL >
</code></pre>

Stacktrace from /agent/_diag

<pre><code>
[2020-11-13 15:00:08Z ERR  Terminal] System.InvalidOperationException: Basic authentication requires a secure connection to the server.
   at Microsoft.VisualStudio.Services.Common.VssBasicCredential.OnCreateTokenProvider(Uri serverUrl, IHttpResponse response)
   at Microsoft.VisualStudio.Services.Common.IssuedTokenCredential.CreateTokenProvider(Uri serverUrl, IHttpResponse response, IssuedToken failedToken)
   at Microsoft.VisualStudio.Services.Common.VssCredentials.TryGetTokenProvider(Uri serverUrl, IssuedTokenProvider& provider)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Location.Client.LocationHttpClient.GetConnectionDataAsync(ConnectOptions connectOptions, Int64 lastChangeId, CancellationToken cancellationToken, Object userState)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.GetConnectionDataAsync(ConnectOptions connectOptions, Int32 lastChangeId, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.Location.VssServerDataProvider.ConnectAsync(ConnectOptions connectOptions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.LocationServer.ConnectAsync(VssConnection jobConnection)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.IsHostedServer(String serverUrl, VssCredentials credentials)
   at Microsoft.VisualStudio.Services.Agent.Listener.Configuration.ConfigurationManager.ConfigureAsync(CommandSettings command)
</code></pre>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b31d4f6c-d16d-2ba1-1294-6aa94e328046
* Version Independent ID: 88aec599-4410-697d-1002-1c41b1c17bb6
* Content: [Run a self-hosted agent in Docker - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops)
* Content Source: [docs/pipelines/agents/docker.md](https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/docker.md)
* Product: **devops**
* Technology: **devops-cicd-agents**
* GitHub Login: @steved0x
* Microsoft Alias: **sdanie**

**Comment by Stahhl** [comment]
Moved this issue to the [azure-pipelines-agent repo](https://github.com/microsoft/azure-pipelines-agent/issues/3167) seemed a better fit.
